# -- 코드를 입력하세요
# SELECT DATE_FORMAT(ofl.SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
# ofl.PRODUCT_ID, onl.USER_ID, ofl.SALES_AMOUNT
# FROM OFFLINE_SALE AS ofl
# JOIN ONLINE_SALE AS onl
# ON ofl.PRODUCT_ID = onl.PRODUCT_ID

# ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

UNION

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;