-- 코드를 작성해주세요
# WITH TMP AS (
#     SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
#             )
            
            
# SELECT I.ID, N.FISH_NAME, I.LENGTH
# FROM TMP AS I
# JOIN FISH_NAME_INFO AS N
# ON I.FISH_TYPE = N.FISH_TYPE

-- ID가 필요하기 때문에 미리 만들어둔 TMP를 쓸수가 없다 ! 
-- GROUP BY 할때 PK를 기준으로는 정렬할수 없기 때문이다.

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO JOIN FISH_NAME_INFO USING(FISH_TYPE)
WHERE (FISH_TYPE, LENGTH) IN (
SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE
)
ORDER BY ID ASC;
